# Generated by Django 2.0.7 on 2018-07-21 21:31

import apps.recipe.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='main_picture',
            field=models.ImageField(upload_to=apps.recipe.files.recipe_main_picture_directory_path),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='secondary_picture',
            field=models.ImageField(null=True, upload_to=apps.recipe.files.recipe_secondary_picture_directory_path),
        ),
    ]
